export enum DashboardNavigationDataEnum {
  FRIDGE = 'FRIDGE',
  MEALS = 'MEALS',
  PRODUCTS = 'PRODUCTS',
  ADD_PRODUCT = 'ADD_PRODUCT',
  SHOPPING_LIST = 'SHOPPING_LIST',
  SETTINGS = 'SETTINGS',
  DAY_PLAN = 'DAY_PLAN',
}
