export enum DashboardNavigationDataEnum {
  FRIDGE = 'FRIDGE',
  MEALS = 'MEALS',
  PRODUCTS = 'PRODUCTS',
  SHOPPING_LIST = 'SHOPPING_LIST',
  SAVED_SHOPPING_LISTS = 'SAVED_SHOPPING_LISTS',
  SETTINGS = 'SETTINGS',
  DAY_PLAN = 'DAY_PLAN',
  MY_DIET = 'MY_DIET',
}
